function Text()
{
	this.mapFr =
	{
		a_id: "Identifiant",
		a_img: "Image",
		a_siz: "Taille",
		a_sir: "Taille aléatoire",
		a_gro: "Vitesse agrandissement",
		a_snd: "Son",
		a_col: "Couleur",
		a_hea: "Santé",
		a_lif: "Durée de vie",
		a_mov: "Mouvement de l'ennemi",
		a_spd: "Vitesse",
		a_spr: "Vitesse aléatoire",
		a_acc: "Accélération",
		a_x: "Position X",
		a_xr: "Position X aléatoire",
		a_y: "Position Y",
		a_yr: "Position Y aléatoire",
		a_an: "Angle",
		a_anr: "Angle aléatoire",
		a_num: "Nombre de balles",
		a_ang: "Ecart d'angle",
		a_xg: "Ecart de X",
		a_yg: "Ecart de Y",
		a_rep: "Répétitions",
		a_rd: "Délai avant répétition",
		a_rx: "Augmenter X",
		a_ry: "Augmenter Y",
		a_ra: "Augmenter angle",
		a_rsi: "Augmenter taille",
		a_rsp: "Augmenter vitesse",
		a_ga: "Angle de gravité",
		a_gf: "Force de gravité",
		a_tri: "Id à déclencher 1",
		a_tri2: "Id à déclencher 2",
		a_trt: "Délai avant déclen. 1",
		a_trt2: "Délai avant déclen. 2",
		a_nxi: "Id prochain",
		a_nxr: "Id prochain aléatoire",
		a_nxh: "Id prochain par santé",
		a_nxd: "Délai du prochain",
		a_sta: "Début",
		a_gho: "Fantôme",
		a_van: "Dissipation",
		a_plx: "Position X du joueur",
		a_ply: "Position Y du joueur",
		a_abp: "Position absolue",
		a_anp: "Vers le joueur",
		a_rel: "Verrou des propriétés",
		a_mut: "Silencieux",
		a_imm: "Immunité aux objets",
		ah_id: "L'identifiant unique de cette attaque, utilisé comme référence pour la création de séquences d'attaques (propriétés de la page 4). Limite: 30 caractères.",
		ah_img: "L'image du projectile.",
		ah_siz: "La taille de base du projectile, de son image et de sa zone de collisions, en pixels. Si défini à 0, le projectile sera invisible, mais pourra tout de même déclencher des attaques. La taille du joueur est de 36 (sa zone de collision n'est qu'un pixel), celle de l'ennemi est de 140.",
		ah_sir: "Une variation aléatoire de la taille du projectile. Par example, si la taille est définie sur 20 et la variation est à 5, alors la taille du projectile sera entre 15 et 25.",
		ah_gro: "Un agrandissement de la taille du projectile en fonction du temps, en pixels par seconde. Si c'est négatif, le projectile rétrécira, et sera détruit si la taille atteint 0.",
		ah_snd: "Le son joué lorsque l'attaque est lancée. Si 'default' est choisi, le son dépendra des propriétés comme la vitesse de répétition et la visibilité.",
		ah_col: "La couleur du projectile.",
		ah_hea: "Si définie sur 1 ou plus, les tirs du joueur peuvent toucher le projectile et réduire sa santé de 1. Le projectile sera détruit si la santé atteint 0, mais il ne le sera pas s'il touche le joueur. Une bombe réduit la santé de 50.",
		ah_lif: "Le délai avant l'expiration du projectile. 1 unité équivaut à 0,01 seconde.",
		ah_mov: "La direction dans laquelle l'ennemi se déplace.",
		ah_spd: "La vitesse du projectile, en pixels par centième de seconde. La vitesse du joueur est de 400.",
		ah_spr: "Une variation aléatoire de la vitesse du projectile. Par example, si la vitesse est définie sur 100 et la variation est à 20, alors la vitesse du projectile sera entre 80 et 120.",
		ah_acc: "L'accélération du projectile, en pixels par seconde. Si c'est négatif, le projectile ralentira, et sera immobile si la vitesse atteint 0.",
		ah_x: "La position horizontale de l'attaque, en pixels, où le projectile apparaît. Si 'Position absolue' et 'Position X du joueur' ne sont pas activées, alors X = 0 sera au centre de l'ennemi.",
		ah_xr: "Une variation aléatoire de la position X de l'attaque.",
		ah_y: "La position verticale de l'attaque, en pixels, où le projectile apparaît. Si 'Position absolue' et 'Position Y du joueur' ne sont pas activées, alors Y = 0 sera au centre de l'ennemi.",
		ah_yr: "Une variation aléatoire de la position Y de l'attaque.",
		ah_an: "La direction de l'attaque. Si 'Vers le joueur' est désactivé, les angles 0, 90, 180 et 270 correspondent respectivement au bas, à la droite, au haut et à la gauche. Les nombres négatifs fonctionnent (-20 = 340).",
		ah_anr: "Une variation aléatoire de la direction de l'attaque. Si c'est 180 ou plus, le projectile ira dans n'importe quelle direction.",
		ah_num: "Le nombre de projectiles tirés simultanément. L'écran est limité à 1000 projectiles.",
		ah_ang: "L'écart d'angle entre chaque projectile, s'il y en a au moins 2.",
		ah_xg: "La distance horizontale entre chaque projectile, s'il y en a au moins 2.",
		ah_yg: "La distance verticale entre chaque projectile, s'il y en a au moins 2.",
		ah_rep: "Le nombre de fois où l'attaque est répétée.",
		ah_rd: "Le délai entre chaque répétition, en centièmes de seconde.",
		ah_rx: "La modification de la position horizontale de l'attaque entre chaque répétition de l'attaque.",
		ah_ry: "La modification de la position verticale de l'attaque entre chaque répétition de l'attaque.",
		ah_ra: "La modification de l'angle de tir entre chaque répétition de l'attaque.",
		ah_rsi: "La modification de la taille des projectiles entre chaque répétition de l'attaque.",
		ah_rsp: "La modification de la vitesse des projectiles chaque répétition de l'attaque.",
		ah_ga: "La gravité est activée s'il y a une valeur. Le projectile sera attiré vers la direction indiquée.",
		ah_gf: "L'augmentation de la vitesse du projectile par la gravité, en pixels par seconde.",
		ah_tri: "L'identifiant de l'attaque à effectuer, à intervalles régulières, par l'attaque en cours, à la position du projectile.",
		ah_trt: "La durée de l'intervalle entre chaque attaque déclenchée, en centièmes de seconde. Doit être supérieure à 0.",
		ah_nxi: "L'identifiant de la prochaine attaque à effectuer après celle-ci (une fois seulement par attaque).",
		ah_nxr: "Plusieurs identifiants d'attaque. La prochaine attaque sera l'une d'entre elles choisie au hasard. Les identifiants sont séparés par des virgules : id1, id2, ...",
		ah_nxh: "Plusieurs identifiants d'attaque. La prochaine attaque est déterminée en fonction de la santé de l'ennemi. Les identifiants sont séparés par des virgules : id1, id2, ... S'il y a 2 attaques, la première sera utilisée au-dessus des 50% de santé de l'ennemi, et la deuxième à moins de 50%. Le nombre de paliers correspond à la longueur de la liste.",
		ah_nxd: "Le délai avant la prochaine attaque, en centièmes de seconde. La plus petite valeur autorisée est 0. Si l'attaque est répétée, le délai commence au premier tir.",
		ah_sta: "L'attaque sera le première a être effectuée. Plusieurs attaques peuvent avoir cette option. Si aucune attaque ne l'a, alors la première de la liste l'aura.",
		ah_gho: "Le projectile n'affecte pas le joueur, il le traversera, il devient un simple effet visuel.",
		ah_van: "Si la durée de vie du projectile est faible, la transparence du projectile augmente avec le temps, jusqu'à devenir totale lors de l'expiration.",
		ah_plx: "La position X = 0 correspond à la position X du joueur.",
		ah_ply: "La position Y = 0 correspond à la position Y du joueur.",
		ah_abp: "X = 0 et Y = 0 correspondent respectivement aux bords gauche et haut de l'écran. Les bords droite et bas sont situés à 600.",
		ah_anp: "L'attaque vise le joueur. L'angle de base est calculé en fonction des positions de l'ennemi et du joueur.",
		ah_rel: "Si l'attaque est répétée, et si 'Vers le joueur' est activé, l'angle de tir reste fixe pendant les répétitions, même si le joueur se déplace.",
		ah_mut: "This attack doesn't emit any sound. The attack is also muted if the bullets appear outside the game screen.",
		ah_imm: "Le projectile n'est pas affecté par les objets utilisés par le joueur (bombe).",
		auto: "Auto.",
		ed_att: "Attaques",
		ed_c_amo: "Quantité",
		ed_c_app: "Apparence",
		ed_c_mn: "Propriétés Principales",
		ed_c_mov: "Mouvement",
		ed_c_pos: "Positionnement",
		ed_c_seq: "Séquençage",
		ed_cop: "Copier",
		ed_del: "Supprimer",
		ed_ie: "Import / Export",
		ed_new: "Nouveau",
		ed_pg: "Page",
		ed_qut: "Quitter l'Editeur",
		ed_qut2: "Quitter l'éditeur ?",
		ed_rep: "A chaque répétition :",
		ed_tst: "Tester le Niveau",
		ie_c: "Fermer",
		ie_e: "Exporter",
		ie_i: "Importer",
		l_1: "Élémentaire de Pierre",
		l_2: "Élémentaire de Pierre",
		l_3: "Élémentaire d'Eau",
		l_4: "Élémentaire d'Eau",
		l_5: "Élémentaire de Plantes",
		l_6: "Élémentaire de Plantes",
		l_7: "Élémentaire de Feu",
		l_8: "Élémentaire de Feu",
		l_9: "Élémentaire de Pierre",
		l_10: "Élémentaire de Pierre",
		l_11: "Élémentaire d'Eau",
		l_12: "Élémentaire d'Eau",
		l_13: "Élémentaire de Plantes",
		l_14: "Élémentaire de Plantes",
		l_15: "Élémentaire de Feu",
		l_16: "Élémentaire de Feu",
		m_e_ent: "Entrer un code de niveau ici",
		m_e_new: "Nouveau Niveau",
		m_e_pl: "Jouer",
		m_l_ed: "Editer",
		m_l_hl: "Niveaux Difficiles",
		m_l_nl: "Niveaux Normaux",
		m_o_fp0: "Afficher FPS: Non",
		m_o_fp1: "Afficher FPS: Oui",
		m_o_lan: "Langue: FR",
		m_o_mok: "Mouvement: Clavier",
		m_o_mos: "Mouvement: Souris",
		m_o_pl1: "Joueurs: 1",
		m_o_pl2: "Joueurs: 2",
		m_o_sn0: "Son: Non",
		m_o_sn1: "Son: Oui",
		m_st: "Démarrer le Jeu",
		m_t_edt: "Editeur",
		m_t_lvl: "Niveaux",
		m_t_opt: "Options",
		no: "Non",
		pg_ba: "Retour",
		pg_en1: "FÉLICITATIONS !",
		pg_en2: "Mode Immortalité débloqué !\nIl est activé par ce bouton\nen bas à droite de l'écran.\nLes balles seront inoffensives !",
		pg_en3: "Au revoir !",
		pg_fail: "Défaite",
		pg_g_d0: "Aucun tir détruit",
		pg_g_d02: "Ne pas détruire de\nprojectile ennemi",
		pg_g_d1: "10 tirs détruits",
		pg_g_d12: "Détruire 10 projectiles\nennemis",
		pg_g_d2: "20 tirs détruits",
		pg_g_d22: "Détruire 20 projectiles\nennemis",
		pg_g_d3: "30 tirs détruits",
		pg_g_d32: "Détruire 30 projectiles\nennemis",
		pg_g_c1: "Combo x100",
		pg_g_c12: "Effectuer un combo de\n100 tirs réussis",
		pg_g_flw: "Sans faute",
		pg_g_flw2: "Ne pas être touché",
		pg_g_ni: "Sans item",
		pg_g_ni2: "Ne pas utiliser d'items",
		pg_g_pc: "Un combo parfait",
		pg_g_pc2: "Vaincre l'ennemi en un seul\ncombo parfait",
		pg_g_win: "Victoire",
		pg_g_win2: "Réussir le niveau",
		pg_h1: "Nv. 1 diff.",
		pg_la: "Dernier nv.",
		pg_lv: "Niveau",
		pg_me: "Menu",
		pg_re: "Rejouer",
		yes: "Oui",
	};

	this.mapEn =
	{
		a_id: "Identifier",
		a_img: "Image",
		a_siz: "Size",
		a_sir: "Random size",
		a_gro: "Growth speed",
		a_snd: "Sound",
		a_col: "Color",
		a_hea: "Health",
		a_lif: "Lifespan",
		a_mov: "Enemy's movement",
		a_spd: "Speed",
		a_spr: "Random speed",
		a_acc: "Acceleration",
		a_x: "X position",
		a_xr: "Random X position",
		a_y: "Y position",
		a_yr: "Random Y position",
		a_an: "Angle",
		a_anr: "Random angle",
		a_num: "Amount of bullets",
		a_ang: "Angle gap",
		a_xg: "X gap",
		a_yg: "Y gap",
		a_rep: "Repetitions",
		a_rd: "Repeat delay",
		a_rx: "Increase X",
		a_ry: "Increase Y",
		a_ra: "Increase angle",
		a_rsi: "Increase size",
		a_rsp: "Increase speed",
		a_ga: "Gravity angle",
		a_gf: "Gravity force",
		a_tri: "Trigger attack 1",
		a_tri2: "Trigger attack 2",
		a_trt: "Trigger delay 1",
		a_trt2: "Trigger delay 2",
		a_nxi: "Next attack",
		a_nxr: "Next attack (random)",
		a_nxh: "Next att. (by health)",
		a_nxd: "Next attack delay",
		a_sta: "Start",
		a_gho: "Ghost",
		a_van: "Vanish effect",
		a_plx: "Player's X position",
		a_ply: "Player's Y position",
		a_abp: "Absolute position",
		a_anp: "Towards player",
		a_rel: "Locked properties",
		a_mut: "Muted",
		a_imm: "Item immunity",
		ah_id: "The attack's unique identifier, required for the creation of attack sequences (using the 'Next' and 'Trigger' properties). Limit: 30 characters.",
		ah_img: "The bullet's image number.",
		ah_siz: "The size of the bullet, its image and its collision box, in pixels. If set to 0, the bullet is invisible, but it can still trigger attacks. The player's size is 36 (but its collision box is just a single pixel) and the enemy's size is 140.",
		ah_sir: "A random bullet size alteration. For example, if size is set to 20 and random size is set to 5, then the bullet's actual size can be any value between 15 and 25.",
		ah_gro: "The bullet size's increase in pixels per second. If the value is negative, the bullet shrinks, and it is destroyed if its size reaches 0.",
		ah_snd: "The sound played when the attack starts. If 'default' is selected, the sound depends on the bullet properties like the repetition delay and the visibility.",
		ah_col: "The bullet's color.",
		ah_hea: "If set to 1 or more, the player's shots can collide with the bullet and reduce its health by 1. The bullet is destroyed if its health reaches 0, however, it isn't if it collides with the player. A bomb inflicts 50 damage.",
		ah_lif: "The delay before the bullet's expiration. 1 unit equals 0.01 second.",
		ah_mov: "If enabled, the enemy starts moving towards the specified location.",
		ah_spd: "The bullet's speed in pixels per frame. The player's speed is 400.",
		ah_spr: "A random bullet speed alteration. For example, if speed is set to 100 and random speed is set to 20, then the bullet's actual speed can be any value between 80 and 120.",
		ah_acc: "The bullet speed's increase in pixels per second. If the value is negative, the bullet slows down, and it stops moving if its speed reaches 0.",
		ah_x: "The attack's horizontal position in pixels, where bullets spawn. If neither 'Absolute pos.' nor 'Player's X pos' is used, then X = 0 is the center of the enemy's image.",
		ah_xr: "A random bullet horizontal position alteration.",
		ah_y: "The attack's vertical position in pixels, where bullets spawn. If neither 'Absolute pos.' nor 'Player's Y pos' is used, then Y = 0 is the center of the enemy's image.",
		ah_yr: "A random bullet vertical position alteration.",
		ah_an: "The attack's direction. 0 is bottom, 90 is right, 180 is top and 270 is left. Negative numbers are allowed here (-20 is the same as 340).",
		ah_anr: "A random bullet direction alteration. If defined to 180 or more, the bullet may travel in any direction.",
		ah_num: "The amount of bullets shot simultaneously. The game allows up to 1000 bullets on the screen.",
		ah_ang: "The angle difference between each bullet if this attack contains more than 1 bullet.",
		ah_xg: "The horizontal gap between each bullet if this attack contains more than 1 bullet.",
		ah_yg: "The vertical gap between each bullet if this attack contains more than 1 bullet.",
		ah_rep: "The number of times this attack must be repeated.",
		ah_rd: "The delay, in hundredth of a second, between each attack.",
		ah_rx: "A value that increases the attack's X position after each shot.",
		ah_ry: "A value that increases the attack's Y position after each shot.",
		ah_ra: "A value that increases the attack's direction after each shot.",
		ah_rsi: "A value that increases the bullet's size after each shot.",
		ah_rsp: "A value that increases the bullet's speed after each shot.",
		ah_ga: "The gravity is enabled by entering any value here. The bullet is attracted towards the specified direction.",
		ah_gf: "The gravity increases the bullet's speed by this value each second.",
		ah_tri: "The identifier of an attack to be constantly triggered by each bullet. The selected attack starts from the current bullet's position.",
		ah_trt: "The delay between two triggered attacks. Must be higher than 0.",
		ah_nxi: "The identifier of the next attack to perform after the current one. Unlike 'Trigger', an attack can schedule only one next attack.",
		ah_nxr: "A list of attack identifiers, the game will randomly choose one attack. The identifiers are separated by commas: id1, id2, ...",
		ah_nxh: "A list of attack identifiers, the game will choose one attack according to the enemy's health. The identifiers are separated by commas: id1, id2, ... If the list contains 2 attacks, the first one is used if the enemy's health is over 50% and the second one if the health is 50% or less. The health thresholds are defined by the list's length.",
		ah_nxd: "The delay before the next attack. The lowest allowed value is 0. If the attack is repeated, the timer starts when the first shot occurs.",
		ah_sta: "This attack occurs first. It is possible to use this option for more than one attack. If it is never used, then it is granted to the first attack in the list.",
		ah_gho: "The bullet is harmless and travels through the player.",
		ah_van: "If the bullet is about to reach the end of its life, this gives it a vanishing effect.",
		ah_plx: "The X = 0 position is set to the player's X position.",
		ah_ply: "The Y = 0 position is set to the player's Y position.",
		ah_abp: "The X = 0 and Y = 0 positions are set to the game screen edges, instead of the enemy's position. X = 0 is the left edge, X = 600 is the right edge, Y = 0 is the top edge, Y = 600 is the bottom edge.",
		ah_anp: "The shot aims at the player. The bullet's direction is based on the enemy's and the player's positions.",
		ah_rel: "This locks the attack's direction and position while shots are being repeated. This means that the attack ignores the player's movement.",
		ah_mut: "This attack doesn't emit any sound. The attack is also muted if the bullets appear outside the game screen.",
		ah_imm: "The bullets are not affected by the items (bomb) used by the player.",
		auto: "Auto.",
		ed_att: "Attacks",
		ed_c_amo: "Amount",
		ed_c_app: "Appearance",
		ed_c_mn: "Main Properties",
		ed_c_mov: "Movement",
		ed_c_pos: "Positioning",
		ed_c_seq: "Sequencing",
		ed_cop: "Copy",
		ed_del: "Delete",
		ed_ie: "Import / Export",
		ed_new: "New",
		ed_pg: "Page",
		ed_qut: "Quit Editor",
		ed_qut2: "Quit the editor?",
		ed_rep: "When the attack is repeated:",
		ed_tst: "Test Level",
		ie_c: "Close",
		ie_e: "Export",
		ie_i: "Import",
		l_1: "Stone Elemental",
		l_2: "Stone Elemental",
		l_3: "Water Elemental",
		l_4: "Water Elemental",
		l_5: "Plant Elemental",
		l_6: "Plant Elemental",
		l_7: "Fire Elemental",
		l_8: "Fire Elemental",
		l_9: "Stone Elemental",
		l_10: "Stone Elemental",
		l_11: "Water Elemental",
		l_12: "Water Elemental",
		l_13: "Plant Elemental",
		l_14: "Plant Elemental",
		l_15: "Fire Elemental",
		l_16: "Fire Elemental",
		m_e_ent: "Enter level code here",
		m_e_new: "New Level",
		m_e_pl: "Play",
		m_l_ed: "Edit",
		m_l_hl: "Hard Levels",
		m_l_nl: "Normal Levels",
		m_o_fp0: "Show FPS: Off",
		m_o_fp1: "Show FPS: On",
		m_o_lan: "Language: ENG",
		m_o_mok: "Move with Keyboard",
		m_o_mos: "Move with Mouse",
		m_o_pl1: "Players: 1",
		m_o_pl2: "Players: 2",
		m_o_sn0: "Sound: Off",
		m_o_sn1: "Sound: On",
		m_st: "Start the Game",
		m_t_edt: "Editor",
		m_t_lvl: "Levels",
		m_t_opt: "Options",
		no: "No",
		pg_ba: "Back",
		pg_en1: "WELL PLAYED!",
		pg_en2: "The God Mode has been unlocked!\nEnable it with this button in\nthe bottom right corner.\nThis makes bullets harmless!",
		pg_en3: "Thanks for playing!",
		pg_fail: "Defeated",
		pg_g_d0: "No bullets killed",
		pg_g_d02: "Do not destroy any\nenemy bullet",
		pg_g_d1: "10 bullets killed",
		pg_g_d12: "Destroy 10 enemy bullets",
		pg_g_d2: "20 bullets killed",
		pg_g_d22: "Destroy 20 enemy bullets",
		pg_g_d3: "30 bullets killed",
		pg_g_d32: "Destroy 30 enemy bullets",
		pg_g_c1: "Combo x100",
		pg_g_c12: "Perform a 100-hits combo",
		pg_g_flw: "Flawless",
		pg_g_flw2: "Do not get hit",
		pg_g_ni: "No item used",
		pg_g_ni2: "Do not use any item",
		pg_g_pc: "One perfect combo",
		pg_g_pc2: "Kill the enemy in one\nperfect combo",
		pg_g_win: "Victory",
		pg_g_win2: "Complete the level",
		pg_h1: "Hard lv. 1",
		pg_la: "Last level",
		pg_lv: "Level",
		pg_me: "Menu",
		pg_re: "Replay",
		yes: "Yes",
	};
}

Text.prototype.get = function(id, args)
{
	var ret;

	if (lang == "fr")
		ret = this.mapFr[id];
	if (lang == "en")
		ret = this.mapEn[id];

	if (args != undefined)
		for (var i = 1; i < args.length + 1; i++)
			ret = ret.replace("$" + i, args[i - 1]);

	return ret;
}